global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets:
          - localhost:8000
  -  job_name: 'node'
     static_configs:
       - targets:
           - localhost:9100